name: client 
description: Client for Gazelle project.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.5.2

dependencies:
  gazelle_serialization: ^0.1.1
  gazelle_client: ^0.4.0+1
  models:
    path: ../models

dev_dependencies:
  lints: ">=2.1.0 <4.0.0"
  test: ^1.24.0
