name: server 
description: A new Gazelle project.
version: 0.1.0
publish_to: "none"

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  gazelle_core: ^0.7.0+1
  models:
    path: ../models

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0